### ISSUE TITLE
Unable to import Key dumps

### ISSUE THREAD

**Issue by atMaarten** [wvengen/ovc-tools#3]
I am unable to import the keys of my OVC. I toke the a-key.dump file, renamed it to a-key.farebotkeys emailed it to myself as in the read me. 

When I open the file on my phone a popup comes op with title "Add Key" and text "Tap a card". When I tap the OVC corresponding with the dump file Farebot gives the message Unsupported Tag.

![screenshot_2014-05-05-12-15-45 2](https://cloud.githubusercontent.com/assets/5883842/2876926/b43eea10-d43f-11e3-8625-814f64e550cc.png)
![screenshot_2014-05-05-12-16-24](https://cloud.githubusercontent.com/assets/5883842/2876925/b43deff2-d43f-11e3-92bf-88449775969d.png)

**Comment by micolous** [comment]
You have a phone that doesn't support Mifare Classic.  Only NXP/Phillips NFC chipsets can read Mifare Classic.

**Comment by wvengen** [comment]
Thanks :)
Closing issue because this repository is not about farebot.
